# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
- azure-pipelines

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Azure Pipelines with Ubuntu!
  displayName: 'ğŸ¦… ğŸ§'

- task: HawkScanInstall@1
  inputs:
    version: 'latest'

- task: RunHawkScan@1
  inputs:
    configFile: 'stackhawk.yml'
    version: 'latest'
  env:
    HAWK_API_KEY: $(HAWK_API_KEY) # the recommended way to map to an env variable
    APP_ENV: azure-pipelines

