name: HawkScan Demo
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  hawkscan:
    name: HawkScan
    runs-on: ubuntu-latest
    permissions:      
      security-events: write
      packages: read
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@v2
      # - uses: actions/setup-java@v4
      #   with:
      #     distribution: 'temurin'
      #     java-version: '17'
      # - name: Download and run JavaSpringVulny release jar
      #   run: |
      #     curl -Ls https://github.com/kaakaww/javaspringvulny/releases/download/0.2.0/java-spring-vuly-0.2.0.jar -o ./java-spring-vuly-0.2.0.jar
      #     java -jar ./java-spring-vuly-0.2.0.jar &
      # - name: Build and run JavaSpringVulny (slower)
      #   run: |
      #     ./gradlew build
      #     ./gradlew bootRun &
      - name: Set up Docker
        uses: docker/setup-docker-action@v4
      - name: Build and run JavaSpringVulny (Docker)
        run: docker-compose up --detach
      - name: Run HawkScan
        env:
          HAWK_ENV: GitHub Actions
          COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
          BRANCH_NAME: ${{ github.head_ref }}
          NO_COLOR: true
          NO_PROGRESS: true
          SARIF_ARTIFACT: true
        continue-on-error: true
        uses: stackhawk/hawkscan-action@v2
        with:
          apiKey: ${{ secrets.HAWK_API_KEY }}
          githubToken: ${{ github.token }}
      - name: Verify SARIF file
        run: |
          ls stackhawk.sarif || true
          echo === vvv stackhawk.sarif contents vvv === || true
          cat stackhawk.sarif || true
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: stackhawk.sarif
          category: StackHawk

